# 1-0-0 Initial Release (Yellow Color Scheme, Minimal Example Work)
# 2-0-0 1 Year Update (Designed for Employers)
# 2-0-1 Added Mobile Responsiveness
# 3-0-0 Redesign
# 4-0-0 Redesign

application: larcolabs
version: 4-0-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

- url: /playground
  static_dir: playground

- url: /portfolio/(sealed|kfe|jlarco)
  static_files: templates/samples/\1.html
  upload: templates/samples/\1.html

- url: .*
  static_files: templates/landing.html
  upload: templates/landing.html

libraries:
- name: webapp2
  version: "2.5.1"

skip_files:
- ^assets(/.*)?$