# 1-0-0 Initial Release (Yellow Color Scheme, Minimal Example Work)
# 2-0-0 1 Year Update (Designed for Employers)
# 2-0-1 Added Mobile Responsiveness
# 2-0-2

application: larcolabs
version: 2-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /images
  static_dir: images
- url: /resources
  static_dir: resources

- url: .*
  script: app.app

libraries:
- name: webapp2
  version: "2.5.1"
